[package]
name = "dropseed"
version = "0.0.0"
edition = "2021"
authors = ["Billy Messenger <BillyDM@tutamail.com>"]
license = "GPL-3.0"
keywords = ["audio", "graph", "daw", "plugin", "host"]
categories = ["multimedia::audio"]
description = "The DAW audio graph engine used in Meadowlark (placeholder)"
documentation = "https://docs.rs/dropseed"
repository = "https://github.com/MeadowlarkDAW/dropseed"
readme = "README.md"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = ["clap-host", "cpal-backend"]
clap-host = ["libloading", "globwalk", "dirs"]
cpal-backend = ["cpal"]
cpal-asio = ["cpal/asio"]

[workspace]
members = [
    "examples/basic-daw-example",
]

[dependencies]
meadowlark-core-types = "0.1"
audio-graph = { git = "https://github.com/MeadowlarkDAW/audio-graph", branch = "main" }
clap-sys = { git = "https://github.com/glowcoil/clap-sys.git", rev = "362c89d22ef7aa7c30b0e8ffa2d9a0ee2dd7897b" }
dirs = { version = "4.0", optional = true }
raw-window-handle = "0.4"
basedrop = "0.1"
smallvec = "1.7"
bitflags = "1.3"
crossbeam = "0.8"
rtrb-basedrop = "0.1"
maybe_atomic_refcell = { version = "0.3", features = [] }
atomic_refcell = "0.1"
fnv = "1.0"
log = "0.4"
thread-priority = "0.8"
cpal = { version = "0.13", optional = true }
libloading = { version = "0.7", optional = true }
globwalk = { version = "0.8", optional = true }

[dev-dependencies]
fast_log = "1.5.16"