[package]
name = "rusty-daw-engine"
version = "0.0.0"
edition = "2021"
authors = ["Billy Messenger <BillyDM@tutamail.com>"]
license = "GPL-3.0"
keywords = ["audio", "graph", "daw", "plugin", "host"]
categories = ["multimedia::audio"]
description = "The RustyDAW DAW engine (placeholder)"
documentation = "https://docs.rs/rusty-daw-engine"
repository = "https://github.com/RustyDAW/rusty-daw-engine"
readme = "README.md"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rusty-daw-core = { path = "../rusty-daw-core" }
#audio-graph = { git = "https://github.com/MeadowlarkDAW/audio-graph", branch = "main" }
audio-graph = { path = "../audio-graph" }
clap-sys = { git = "https://github.com/glowcoil/clap-sys.git", branch = "master" }
raw-window-handle = "0.4"
basedrop = "0.1"
smallvec = "1.7"
bitflags = "1.3"
fnv = "1.0"
log = "0.4"