[package]
name = "dropseed"
version = "0.0.0"
edition = "2021"
authors = ["Billy Messenger <BillyDM@tutamail.com>"]
license = "GPL-3.0"
keywords = ["audio", "graph", "daw", "plugin", "host"]
categories = ["multimedia::audio"]
description = "The DAW audio graph engine used in Meadowlark (placeholder)"
documentation = "https://docs.rs/dropseed"
repository = "https://github.com/MeadowlarkDAW/dropseed"
readme = "README.md"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace]
members = ["examples/test-host"]

[features]
default = ["clap-host", "cpal-backend"]
clap-host = ["globwalk", "dirs"]
cpal-backend = ["cpal"]
cpal-asio = ["cpal/asio"]

[dependencies]
meadowlark-core-types = { git = "https://github.com/MeadowlarkDAW/meadowlark-core-types", branch = "main" }
audio-graph = { git = "https://github.com/MeadowlarkDAW/audio-graph", branch = "main" }
clack-host = { git = "https://github.com/prokopyl/clack", rev = "46574a236306ded5afadc5285080faf65b99e26e" }
clack-extensions = { git = "https://github.com/prokopyl/clack", features = ["clack-host", "audio-ports", "log", "note-ports", "params", "state", "thread-check"], rev = "46574a236306ded5afadc5285080faf65b99e26e" }
dirs = { version = "4.0", optional = true }
raw-window-handle = "0.4"
basedrop = "0.1"
smallvec = "1.7"
bitflags = "1.3"
crossbeam = "0.8"
rtrb = "0.2"
atomic_refcell = "0.1"
fnv = "1.0"
log = "0.4"
thread-priority = "0.8"
cpal = { version = "0.13", optional = true }
globwalk = { version = "0.8", optional = true }
serde = { version = "1.0", features = ["derive"] }
# TODO: Add two features: one to use the symphonia dependency, and one to use the non-open source formats with symphonia.
symphonia = { version = "0.5", features = ["flac", "mkv", "ogg", "pcm", "vorbis", "wav", "mp3", "aac", "alac"]}
twox-hash = "1.6"
bincode = "1.3.3"
#samplerate-rs = "0.1"
#samplerate-rs = { path = "../samplerate-rs" }
samplerate-rs = { git = "https://github.com/MeadowlarkDAW/samplerate-rs.git", branch = "master" }
